# SPDX-FileCopyrightText: 2025 2025 Oxyde Contributors
#
# SPDX-License-Identifier: MPL-2.0

[package]
name = "oxyde_theming"
version = "0.1.0"
edition = "2021"
[lib]
path = "src/lib.rs"
[dependencies]
